=== arcticdba/eventtracker/tblEvents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblEvents" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblEvents">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="EventID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="Lq3KmMfNg0iTTrk38Tgn/Q==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAurcqYx82DSJNOuTfxOCf9AAAAACxyTncczOVAAAAAAAAAAAB0AGIA
bABFAHYAZQBuAHQAcwAAAAAAAAAd7f84BACWSrchOCJJLkA3BwAAAC6typjHzYNI
k065N/E4J/1EAGEAdABlAEUAbgBkAAAAAAAAALRXW0niKjVAg2wtxX6nhO0HAAAA
Lq3KmMfNg0iTTrk38Tgn/UUAdgBlAG4AdABJAEQAAAAAAAAAzAiIvPf2S0WYOEIj
ib8P/gcAAAAurcqYx82DSJNOuTfxOCf9RABhAHQAZQBTAHQAYQByAHQAAAAAAAAA
4qmgdK648kOPLQzEZawQOgcAAAAurcqYx82DSJNOuTfxOCf9QwBpAHQAeQAAAAAA
AADboMcLJemqSKDYCOhSyKy+BwAAAC6typjHzYNIk065N/E4J/1DAG8AdQBuAHQA
cgB5AAAAAAAAAOiLKKSzQGJDur2HngJf6JsHAAAALq3KmMfNg0iTTrk38Tgn/UUA
dgBlAG4AdABOAGEAbQBlAAAAAAAAAImseqpF1dpCkEKzyBP4CmkHAAAALq3KmMfN
g0iTTrk38Tgn/UUAdgBlAG4AdABTAHQAYQB0AHUAcwAAAAAAAADIykJdcTK6SZyV
TUxxrBCUBwAAAC6typjHzYNIk065N/E4J/1JAHMAUgBlAG0AbwB0AGUAAAAAAAAA
bApSJFysBUaM4+ErF/f6NQcAAAAurcqYx82DSJNOuTfxOCf9TQBWAFAASwBpAG4A
ZAAAAAAAAACPYpHMHWaTQ5Zi3v0uAOrQBwAAAC6typjHzYNIk065N/E4J/1DAGYA
QwBVAFIATAAAAAAAAACq3iNm/MzdTKq+MA1Zd8LIBwAAAC6typjHzYNIk065N/E4
J/1DAGYAQwBMAGEAcwB0AEQAYQB0AGUAAAAAAAAAYy285RbM/kSdtz8UVGiEqQcA
AAAurcqYx82DSJNOuTfxOCf9TABvAGcAaQBuAEYAbwByAEMARgBDAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="OrderBy" type="12" value="[tblEvents].[DateEnd]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="EventID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tFdbSeIqNUCDbC3FfqeE7Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DateStart" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="zAiIvPf2S0WYOEIjib8P/g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1920"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="DateEnd" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="He3/OAQAlkq3ITgiSS5ANw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="City" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4qmgdK648kOPLQzEZawQOg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Country" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="26DHCyXpqkig2AjoUsisvg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3900"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="EventName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="6IsopLNAYkO6vYeeAl/omw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2713"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="EventStatus" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="iax6qkXV2kKQQrPIE/gKaQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="DefaultValue" type="12" value="&quot;Registered&quot;"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="IsRemote" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yMpCXXEyukmclU1McawQlA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MVPKind" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="bApSJFysBUaM4+ErF/f6NQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Value List"/>
<od:fieldProperty name="RowSource" type="12" value="&quot;Speaking (Conference)&quot;;&quot;Speaking (User Group)&quot;;&quot;Speaking (Local)&quot;"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="DefaultValue" type="12" value="&quot;Speaking (Conference)&quot;"/>
<od:fieldProperty name="ListRows" type="3" value="16"/>
<od:fieldProperty name="ListWidth" type="10" value="0twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CfCURL" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="j2KRzB1mk0OWYt79LgDq0A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="7185"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CfCLastDate" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qt4jZvzM3UyqvjANWXfCyA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="LoginForCFC" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Yy285RbM/kSdtz8UVGiEqQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== arcticdba/eventtracker/tblEvents.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblEvents.xsd" generated="2026-01-16T06:41:56">
<tblEvents>
<EventID>4</EventID>
<DateStart>2016-08-27T00:00:00</DateStart>
<DateEnd>2016-08-27T00:00:00</DateEnd>
<City>Gothenburg</City>
<Country>Sweden</Country>
<EventName>SQL Saturday #536</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>17</EventID>
<DateStart>2016-09-03T00:00:00</DateStart>
<DateEnd>2016-09-03T00:00:00</DateEnd>
<City>Oslo</City>
<Country>Norway</Country>
<EventName>SQL Saturday #532</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>19</EventID>
<DateStart>2016-09-10T00:00:00</DateStart>
<DateEnd>2016-09-10T00:00:00</DateEnd>
<City>Cambridge</City>
<Country>United Kingdom</Country>
<EventName>SQL Saturday #520</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>5</EventID>
<DateStart>2016-11-16T00:00:00</DateStart>
<DateEnd>2016-11-17T00:00:00</DateEnd>
<City>Stockholm</City>
<Country>Sweden</Country>
<EventName>TechDays Sweden</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>18</EventID>
<DateStart>2017-02-25T00:00:00</DateStart>
<DateEnd>2017-02-25T00:00:00</DateEnd>
<City>Pordenone</City>
<Country>Italy</Country>
<EventName>SQL Saturday #589</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>16</EventID>
<DateStart>2017-03-11T00:00:00</DateStart>
<DateEnd>2017-03-11T00:00:00</DateEnd>
<City>Lisbon</City>
<Country>Portugal</Country>
<EventName>SQL Saturday #583</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>22</EventID>
<DateStart>2017-03-18T00:00:00</DateStart>
<DateEnd>2017-03-18T00:00:00</DateEnd>
<City>Reykjavik</City>
<Country>Iceland</Country>
<EventName>SQL Saturday #602</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>21</EventID>
<DateStart>2017-03-18T00:00:00</DateStart>
<DateEnd>2017-03-18T00:00:00</DateEnd>
<City>Belgrade</City>
<Country>Serbia</Country>
<EventName>SQL Saturday #601</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>6</EventID>
<DateStart>2017-05-18T00:00:00</DateStart>
<DateEnd>2017-05-18T00:00:00</DateEnd>
<City>Linköping</City>
<Country>Sweden</Country>
<EventName>.NET User Group Meeting</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>23</EventID>
<DateStart>2017-05-20T00:00:00</DateStart>
<DateEnd>2017-05-20T00:00:00</DateEnd>
<City>Kyiv</City>
<Country>Ukraine</Country>
<EventName>SQL Saturday #616</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>20</EventID>
<DateStart>2017-05-27T00:00:00</DateStart>
<DateEnd>2017-05-27T00:00:00</DateEnd>
<City>Plovdiv</City>
<Country>Bulgaria</Country>
<EventName>SQL Saturday #599</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>25</EventID>
<DateStart>2017-09-02T00:00:00</DateStart>
<DateEnd>2017-09-02T00:00:00</DateEnd>
<City>Oslo</City>
<Country>Norway</Country>
<EventName>SQL Saturday #667</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>24</EventID>
<DateStart>2017-09-16T00:00:00</DateStart>
<DateEnd>2017-09-16T00:00:00</DateEnd>
<City>Toulouse</City>
<Country>France</Country>
<EventName>SQL Saturday #658</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>7</EventID>
<DateStart>2017-09-23T00:00:00</DateStart>
<DateEnd>2017-09-23T00:00:00</DateEnd>
<City>Gothenburg</City>
<Country>Sweden</Country>
<EventName>SQL Saturday #657</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>29</EventID>
<DateStart>2017-10-25T00:00:00</DateStart>
<DateEnd>2017-10-25T00:00:00</DateEnd>
<City>Stockholm</City>
<Country>Sweden</Country>
<EventName>TechDays Sweden</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>26</EventID>
<DateStart>2017-11-18T00:00:00</DateStart>
<DateEnd>2017-11-18T00:00:00</DateEnd>
<City>Talinn</City>
<Country>Latvia</Country>
<EventName>SQL Saturday #668</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>8</EventID>
<DateStart>2017-11-27T00:00:00</DateStart>
<DateEnd>2017-11-27T00:00:00</DateEnd>
<City>Stockholm</City>
<Country>Sweden</Country>
<EventName>SQL UG</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (User Group)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>9</EventID>
<DateStart>2018-01-19T00:00:00</DateStart>
<DateEnd>2018-01-19T00:00:00</DateEnd>
<City>Vienna</City>
<Country>Austria</Country>
<EventName>SQL Saturday #679</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>10</EventID>
<DateStart>2018-01-30T00:00:00</DateStart>
<DateEnd>2018-02-02T00:00:00</DateEnd>
<City>Oslo</City>
<Country>Norway</Country>
<EventName>Nordic Infrastructure Conference</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>11</EventID>
<DateStart>2018-03-10T00:00:00</DateStart>
<DateEnd>2018-03-10T00:00:00</DateEnd>
<City>Reykjavik</City>
<Country>Iceland</Country>
<EventName>SQL Saturday #704</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>14</EventID>
<DateStart>2018-03-14T00:00:00</DateStart>
<DateEnd>2018-03-14T00:00:00</DateEnd>
<City>Antwerp</City>
<Country>Belgium</Country>
<EventName>IT Proud</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>12</EventID>
<DateStart>2018-03-21T00:00:00</DateStart>
<DateEnd>2018-03-22T00:00:00</DateEnd>
<City>Helsinki</City>
<Country>Finland</Country>
<EventName>TechDays Finland</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>13</EventID>
<DateStart>2018-04-21T00:00:00</DateStart>
<DateEnd>2018-04-21T00:00:00</DateEnd>
<City>Linköping</City>
<Country>Sweden</Country>
<EventName>Global Azure Bootcamp</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Local)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>15</EventID>
<DateStart>2018-04-26T00:00:00</DateStart>
<DateEnd>2018-04-26T00:00:00</DateEnd>
<City>Tel Aviv</City>
<Country>Israel</Country>
<EventName>SQL Saturday #738</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>39</EventID>
<DateStart>2018-05-12T00:00:00</DateStart>
<DateEnd>2018-05-12T00:00:00</DateEnd>
<City>Helsinki</City>
<Country>Finland</Country>
<EventName>SQL Saturday #735</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>28</EventID>
<DateStart>2018-05-22T00:00:00</DateStart>
<DateEnd>2018-05-24T00:00:00</DateEnd>
<City>Antwerp</City>
<Country>Belgium</Country>
<EventName>Techorama BE 2018</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>36</EventID>
<DateStart>2018-05-26T00:00:00</DateStart>
<DateEnd>2018-05-26T00:00:00</DateEnd>
<City>Munich</City>
<Country>Germany</Country>
<EventName>Azure Saturday</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>35</EventID>
<DateStart>2018-05-29T00:00:00</DateStart>
<DateEnd>2018-05-30T00:00:00</DateEnd>
<City>Copenhagen</City>
<Country>Denmark</Country>
<EventName>Intelligent Cloud Conference</EventName>
<EventStatus>Accepted</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>38</EventID>
<DateStart>2018-05-29T00:00:00</DateStart>
<DateEnd>2018-05-31T00:00:00</DateEnd>
<City>Riga</City>
<Country>Latvia</Country>
<EventName>Riga DevDays 2018</EventName>
<EventStatus>Rejected</EventStatus>
<IsRemote>0</IsRemote>
<MVPKind>Speaking (Conference)</MVPKind>
</tblEvents>
<tblEvents>
<EventID>31</EventID>
<DateStart>2018-06-09T00:00:00</DateStart>
<DateEnd>2018-06-09T00:00:00</DateEnd>
<City>Cork</City>
<Country>Ireland</Country>
<EventName>SQL Saturday #742</EventName>
