=== arcticdba/eventtracker/tblSessionEvents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblSessionEvents" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblSessionEvents">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="EventID SessionID " primary="yes" unique="yes" clustered="no" order="asc asc"/>
<od:index index-name="SessionID" index-key="SessionID " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="iv/+gOwD8UKc/h/yvCGsdw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACK//6A7APxQpz+H/K8Iax3AAAAAAZeBSkrDOVAAAAAAAAAAAB0AGIA
bABTAGUAcwBzAGkAbwBuAEUAdgBlAG4AdABzAAAAAAAAACHOD+tr39RPn0pDjH6B
YS0HAAAAiv/+gOwD8UKc/h/yvCGsd0UAdgBlAG4AdABJAEQAAAAAAAAAVBOm/qdp
l0q6ROwV116jDgcAAACK//6A7APxQpz+H/K8Iax3UwBlAHMAcwBpAG8AbgBJAEQA
AAAAAAAAnb9VPCgg9EKYUsMmV1GoUQcAAACK//6A7APxQpz+H/K8Iax3UwB0AGEA
dAB1AHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAA
AAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="EventID" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Ic4P62vf1E+fSkOMfoFhLQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SessionID" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="VBOm/qdpl0q6ROwV116jDg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Status" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nb9VPCgg9EKYUsMmV1GoUQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSource" type="10" value="&quot;Submitted&quot;;&quot;Accepted&quot;;&quot;Rejected&quot;;&quot;Declined&quot;;&quot;Cancelled&quot;;&quot;Withdrawn&quot;"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== arcticdba/eventtracker/tblSessionEvents.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblSessionEvents.xsd" generated="2026-01-16T06:42:16">
<tblSessionEvents>
<EventID>4</EventID>
<SessionID>1</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>5</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>6</EventID>
<SessionID>3</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>7</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>8</EventID>
<SessionID>3</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>9</EventID>
<SessionID>4</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>10</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>10</EventID>
<SessionID>6</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>11</EventID>
<SessionID>6</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>12</EventID>
<SessionID>5</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>13</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>14</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>15</EventID>
<SessionID>4</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>15</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>15</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>15</EventID>
<SessionID>8</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>15</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>16</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>16</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>17</EventID>
<SessionID>1</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>17</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>17</EventID>
<SessionID>10</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>18</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>18</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>19</EventID>
<SessionID>1</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>19</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>19</EventID>
<SessionID>10</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>20</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>20</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>21</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>21</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>22</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>22</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>23</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>23</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>24</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>24</EventID>
<SessionID>3</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>25</EventID>
<SessionID>3</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>25</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>25</EventID>
<SessionID>11</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>26</EventID>
<SessionID>3</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>26</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>26</EventID>
<SessionID>11</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>9</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>9</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>27</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>27</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>27</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>27</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>11</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>8</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>28</EventID>
<SessionID>12</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>29</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>8</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>31</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>31</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>31</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>31</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>31</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>32</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>32</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>32</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>32</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>32</EventID>
<SessionID>2</SessionID>
<Status>Accepted</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>8</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>33</EventID>
<SessionID>12</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>34</EventID>
<SessionID>2</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>34</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>34</EventID>
<SessionID>5</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>34</EventID>
<SessionID>6</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>34</EventID>
<SessionID>9</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>30</EventID>
<SessionID>4</SessionID>
<Status>Rejected</Status>
</tblSessionEvents>
<tblSessionEvents>
<EventID>35</EventID>
